More sofisticated way to set TEXTDOMANDIR b3bp_install.ini renamed to install.ini copy_files function add LOG_LEVEL and NO_COLOR to log.sh

diff --git a/b3bp b/b3bp
--- a/b3bp
+++ b/b3bp
@@ -72,10 +72,10 @@ source install_script.sh
 #-------------------------------------------------------------------------------
 # Localization
 #-------------------------------------------------------------------------------
-export TEXTDOMAINDIR="/usr/share/locale"
-__b3bp_localepath=( "${__b3bp_dir}/locale" "${HOME}/.local/share/locale" )
+export TEXTDOMAINDIR="${__b3bp_dir}/locale"
+__b3bp_localepath=( "${HOME}/.local/share/locale" "/usr/local/share/locale" "/usr/share/locale" )
   for folder in "${__b3bp_localepath[@]}"; do
-    if [[ -d "${folder}" ]]; then
+    if [[ -n $(find "${folder}" -name "${__b3bp_base}.mo") ]]; then
       export TEXTDOMAINDIR="${folder}"
       break
     fi
@@ -104,29 +104,6 @@ __b3bp_requiredtext=$"Required"
 __b3bp_name=$"BASH3 Boilerplate by krisztianmukli"
 __b3bp_version="v1.0.0"
 __b3bp_license=$"Licensed under the MIT license"
-
-#-------------------------------------------------------------------------------
-# Signal trapping and backtracing
-#-------------------------------------------------------------------------------
-function create_tempdir() {
-  (umask 077 && mkdir "${__b3bp_tmpdir}") || emergency $"Could not create temporary directory! Exiting."
-}
-
-function __b3bp_cleanup_before_exit () {
-  rm -rf "${__b3bp_tmpdir}"
-  info $"Cleaning up. Done"
-}
-trap __b3bp_cleanup_before_exit EXIT
-
-# requires `set -o errtrace`
-__b3bp_err_report() {
-    local error_code
-    error_code=${?}
-    error $"Error in ${__file} in function ${1} on line ${2}"
-    exit ${error_code}
-}
-# Uncomment the following line for always providing an error backtrace
-# trap '__b3bp_err_report "${FUNCNAME:-.}" ${LINENO}' ERR
 
 #===============================================================================
 # Functions section
@@ -312,11 +289,6 @@ if [[ "${__b3bp_arg_V:?}" = "1" ]]; then
   display_info "${__b3bp_name}" "${__b3bp_version}" "${__b3bp_license}"
 fi
 
-# install script
-if [[ "${__b3bp_arg_I:?}" = "1" ]]; then
-  install_script "${__b3bp_dir}" "$__b3bp_base"
-fi
-
 #-------------------------------------------------------------------------------
 # Validate required arguments
 #-------------------------------------------------------------------------------
@@ -357,6 +329,29 @@ if [[ "${__b3bp_external_usage:-}" == 1 ]]; then
   unset -v __b3bp_external_usage
   return
 fi
+
+#-------------------------------------------------------------------------------
+# Signal trapping and backtracing
+#-------------------------------------------------------------------------------
+function create_tempdir() {
+  (umask 077 && mkdir "${__b3bp_tmpdir}") || emergency $"Could not create temporary directory! Exiting."
+}
+
+function __b3bp_cleanup_before_exit () {
+  rm -rf "${__b3bp_tmpdir}"
+  info $"Cleaning up. Done"
+}
+trap __b3bp_cleanup_before_exit EXIT
+
+# requires `set -o errtrace`
+__b3bp_err_report() {
+    local error_code
+    error_code=${?}
+    error $"Error in ${__file} in function ${1} on line ${2}"
+    exit ${error_code}
+}
+# Uncomment the following line for always providing an error backtrace
+# trap '__b3bp_err_report "${FUNCNAME:-.}" ${LINENO}' ERR
 
 #-------------------------------------------------------------------------------
 # Call internal functions
